name: alpha

on:
  push:
    branches:
      - master
    tags-ignore:
      - "**"

jobs:
  alpha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # need entire history for `git describe`
          fetch-tags: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt pyinstaller

      - name: Get latest tag suffixed with tag
        id: version
        run: echo "commit_version=$(git describe --tags)" >> $GITHUB_OUTPUT

      - name: Get repo description
        id: desc
        run: echo "desc=$(curl -fsSL ${{ github.api_url }}/repos/${{ github.repository }} | jq -r .description)" >> $GITHUB_OUTPUT

      - name: Substitute version
        run: sed -i 's/__version__/${{ steps.version.outputs.commit_version }}/' vyaml.py

      - name: Build amd64 binary
        run: pyinstaller -F vyaml.py --hidden-import json --target-architecture x86_64 -n vyaml-amd64

      - name: Upload amd64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: vyaml-amd64-${{ steps.version.outputs.commit_version }}
          path: dist/vyaml-amd64

      - name: Build arm64 binary
        run: pyinstaller -F vyaml.py --hidden-import json --target-architecture arm64 -n vyaml-arm64

      - name: Upload arm64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: vyaml-arm64-${{ steps.version.outputs.commit_version }}
          path: dist/vyaml-arm64

      - name: Prepare .deb directories
        run: |
          mkdir -p  mkdir -p .debpkg/vyaml-amd64/usr/local/bin
          mkdir -p  mkdir -p .debpkg/vyaml-arm64/usr/local/bin
          cp dist/vyaml-amd64 .debpkg/vyaml-amd64/usr/local/bin/vyaml
          cp dist/vyaml-arm64 .debpkg/vyaml-arm64/usr/local/bin/vyaml
          chmod +x .debpkg/vyaml-amd64/usr/local/bin/vyaml
          chmod +x .debpkg/vyaml-arm64/usr/local/bin/vyaml

      - name: Build x86_64 deb
        uses: jiro4989/build-deb-action@v3.0.0
        id: deb_amd64
        with:
          package: vyaml
          version: ${{ steps.version.outputs.commit_version }}
          arch: amd64
          maintainer: ${{ github.repository_owner }}
          package_root: .debpkg/vyaml-arm64
          desc: ${{ steps.desc.outputs.desc }}

      - name: Build arm64 deb
        uses: jiro4989/build-deb-action@v3.0.0
        id: deb_arm64
        with:
          package: vyaml
          version: ${{ steps.version.outputs.commit_version }}
          arch: arm64
          maintainer: ${{ github.repository_owner }}
          package_root: .debpkg/vyaml-arm64
          desc: ${{ steps.desc.outputs.desc }}

      - name: Upload amd64 deb artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.deb_amd64.outputs.file_name }}

      - name: Upload arm64 deb artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.deb_arm64.outputs.file_name }}
